### ISSUE TITLE
[ErrorException] Invalid argument supplied for foreach() when running `php artisan station:build`

### ISSUE THREAD

**Issue by gamergemparq** [LifeboyTech/station#1]
Hi,

Firstly, thanks for making a great addition for Laravel :D 

I've tried installing Station today and followed the steps-by-steps under **Configuration & Setup**. But when I'm at step #4 and ran the above command, the aforementioned error appeared. 

My Laravel installation is pretty vanilla, no other packages included yet. The only thing I did that was not part of your tutorial was to edit the _name_ value in `/app/config/packages/canary/station/_app.php`. But even after reverting to the original value, the error still happens.

Screenshot : 
![image](https://cloud.githubusercontent.com/assets/380777/6595044/6cead5f8-c821-11e4-98c6-89fcf6a60dad.png)

Any advice is highly appreciated :D

**Comment by phirschybar** [comment]
@gamergemparq - we are still in the process of converting the L4 version (https://github.com/thecanarycollective/station) of this package to L5. I am going to put a note to that effect on the readme. Sorry for the trouble. I hope to have this upgraded within the next few weeks.

**Comment by phirschybar** [comment]
New docs: http://station.readthedocs.org/

**Comment by vietz-dev** [comment]
Hello I have the same issue, please help.
Thank you

**Comment by phirschybar** [comment]
@kiesman99 have you updated composer.json to latest version?

**Comment by vietz-dev** [comment]
@phirschybar Yeah I've updated the composer.json.
I've followed your step-by-step guide in the documentation.
