### ISSUE TITLE
Standard View page L4

### ISSUE THREAD

**Issue by danmartuszewski** [LifeboyTech/station#2]
Hi,
I'm using it with L4. 
1. Is there anything like standard view page, not edit, just view with edit button.
2. How can I add link to sidebar that goes directly to my controller?

Thanks

**Comment by danmartuszewski** [comment]
Moved to L4 version
https://github.com/thecanarycollective/station/issues/5

**Comment by phirschybar** [comment]
@dmartuszewski - yes there are overrides. I will add some documentation on this ASAP.
