### ISSUE TITLE
null boolean fields on creation

### ISSUE THREAD

**Issue by chas-mcmahon** [LifeboyTech/station#5]
I'm on Laravel 5.2 and can't create new panels with boolean fields that are unchecked. Currently dealing with it by adding `->nullable()` on the those fields in my migrations. Once the panel is created, though, I can turn the booleans on and off with no problems.

**Comment by phirschybar** [comment]
I have noticed this too. I will have `->nullable()` added to the migration automatically when using the build command.

**Comment by chas-mcmahon** [comment]
Awesome, thank you.

**Comment by phirschybar** [comment]
This has been solved by: https://github.com/LifeboyTech/station/commit/9fd53bec9ccecb0eac37bebd1f4491862c4c06f3
