### ISSUE TITLE
Subpanel error at list view

### ISSUE THREAD

**Issue by chas-mcmahon** [LifeboyTech/station#7]
When I try to display subpanel data in the parent's list view, I get an undefined index error coming from line 13 of `station/src/views/partials/list_item_row_content.blade.php`. Specifically, there's no 'name' index on $sub_data.

I'm getting around it by just not displaying that data in the list view. Everything else around the subpanel seems to be ok.

**Comment by phirschybar** [comment]
Ah. The system assumes that one of your subpanel elements will have a `name` key. Going to remove this assumption.

**Comment by phirschybar** [comment]
Fixed with: https://github.com/LifeboyTech/station/commit/e7979495d625a44281628d47b9feefb8c2d675dc
